### ISSUE TITLE
(Basic Python - Operators) Missing content, conflicting dir prefixes

### ISSUE THREAD

**Issue by svarlamov** [exlskills/course-python-introduction#1]
- [x] Both https://github.com/exlskills/course-python-introduction/tree/master/01_Basic%20Python/03_Operators/03_Identity%20Operators and https://github.com/exlskills/course-python-introduction/tree/master/01_Basic%20Python/03_Operators/03_Membership%20Operators share the same prefix of `03_`. They should probably be split up

- [x] https://github.com/exlskills/course-python-introduction/blob/master/01_Basic%20Python/03_Operators/03_Membership%20Operators/index.md is missing content

- [x] https://github.com/exlskills/course-python-introduction/blob/master/01_Basic%20Python/05_Final%20Exam/04_Question%204/index.prob.md the question seems to be incorrect (answer options/questions don't fit together)

**Comment by Esaslow** [comment]
Deleted the identity operators folder
Fixed the question that seemed out of place (definitely was not the right question)
